version: '2.29'

networks:
  cicd-net:

volumes:
  jenkins_home:
    driver: local
  gitea:
    driver: local

services: 
  jenkins: 
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8066:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - cicd-net

  gitea: 
    image: gitea/gitea:latest-rootless
    container_name: gitea
    restart: always
    ports:
      - "300:3000"
      - "12345:2222"
    volumes:
      -  gitea:/data
      -  gitea:/config
    networks:
      - cicd-net

  # 
  # sonarqube:
  #   image: sonarqube:latest
  #   container_name: sonarqube
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - cicd-net